stages:
 - lint
 - build
 - deploy

default:
  image: node:22-alpine

lint_frontend:
  stage: lint
  cache:
    - key:
        files:
          - node_modules.lock
      paths:
        - ./node_modules
  script:
    - yarn install
    - yarn run compile
    - yarn run lint

build_frontend:
  stage: build
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - gcloud builds submit --config build.prod.yaml

deploy_frontend:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - >-
      gcloud run deploy antimony-prod
      --set-env-vars "PROXY_URL=https://antimony-backend-prod-491689167898.europe-west1.run.app"
      --image europe-west1-docker.pkg.dev/antimony-438914/antimony/antimony-prod:latest
      --allow-unauthenticated
      --region=europe-west1
      --memory=2Gi
      --ingress=all
      --port 8100
      --cpu=1

build_frontend_offline:
  stage: build
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - gcloud builds submit --config build-offline.prod.yaml

deploy_frontend_offline:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - >-
      gcloud run deploy antimony-offline-prod
      --image europe-west1-docker.pkg.dev/antimony-438914/antimony/antimony-offline-prod:latest
      --allow-unauthenticated
      --region=europe-west1
      --memory=2Gi
      --ingress=all
      --port 8100
      --cpu=1

build_backend:
  stage: build
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - cd ./server
    - gcloud builds submit --config build.prod.yaml

deploy_backend:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - >-
      gcloud run deploy antimony-backend-prod
      --image europe-west1-docker.pkg.dev/antimony-438914/antimony/antimony-backend-prod:latest
      --allow-unauthenticated
      --region=europe-west1
      --memory=2Gi
      --ingress=all
      --port 3000
      --cpu=1

